services:
  - type: web
    name: serendipity-backend
    runtime: dotnet
    runtimeVersion: "8"
    buildCommand: "cd backend && dotnet publish -c Release -o out"
    startCommand: "cd backend && dotnet ./out/ElMediadorDeSofia.dll"
    envVars:
      - key: DATABASE_URL
        scope: build,runtime
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: "http://0.0.0.0:10000"
    port: 10000
    healthCheckPath: /health
